name: Moderate Discussion Comments

on:
  discussion_comment:
    types: [created]

jobs:
  moderate-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r moderation/requirements.txt

      - name: Run moderation check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python moderation/check_comment.py "${{ github.event.comment.body }}" "${{ github.event.comment.user.login }}" "${{ github.event.discussion.html_url }}" "${{ github.event.comment.node_id }}" "${{ github.repository }}"
