name: GitHub Discussion & Comment Moderation

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  discussions: write

jobs:
  moderate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r moderation/requirements.txt

    - name: Moderate with Gemini
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: python moderation/moderate.py
